name: Configurator Tests

# Based on https://github.com/mvdan/github-actions-golang
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
# do we need to Install dependencies?
#       run: go get .
      - uses: actions/checkout@v3
      - run: go test ./...
